FROM node:20-alpine
WORKDIR /app
COPY ../backend/package.json ../backend/pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install
COPY ../backend .
COPY ../shared ../shared
EXPOSE 3000
CMD ["pnpm", "run", "dev:backend"]
