FROM node:18-alpine
WORKDIR /app/backend
COPY backend/package.json backend/yarn.lock ../shared/package.json ../shared/yarn.lock ./
RUN yarn install --frozen-lockfile
COPY backend ./
COPY shared ../shared
ENV NODE_ENV=production
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]
