FROM node:18-alpine
WORKDIR /app
COPY package.json yarn.lock ./
COPY backend/package.json ./backend/
COPY shared/package.json ./shared/
RUN yarn install --frozen-lockfile
COPY backend ./backend
COPY shared ./shared
WORKDIR /app/backend
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]
