FROM node:18-alpine
WORKDIR /app
COPY package.json yarn.lock ./
COPY frontend/package.json ./frontend/
COPY shared/package.json ./shared/
RUN yarn install --frozen-lockfile
COPY frontend ./frontend
COPY shared ./shared
WORKDIR /app/frontend
EXPOSE 5173
CMD ["yarn", "dev"]
