/**
 * Design Tokens
 * Auto-generated by WF2.75
 * DO NOT EDIT MANUALLY
 */

export const designTokens = {
  "colors": {
    "primary": {
      "50": "#e3f2fd",
      "100": "#bbdefb",
      "200": "#90caf9",
      "300": "#64b5f6",
      "400": "#42a5f5",
      "500": "#2196f3",
      "600": "#1e88e5",
      "700": "#1976d2",
      "800": "#1565c0",
      "900": "#0d47a1",
      "950": "#0a3b8f"
    },
    "secondary": {
      "50": "#f1f8e9",
      "100": "#dcedc8",
      "200": "#c5e1a5",
      "300": "#aed581",
      "400": "#9ccc65",
      "500": "#8bc34a",
      "600": "#7cb342",
      "700": "#689f38",
      "800": "#558b2f",
      "900": "#33691e",
      "950": "#2a5a17"
    },
    "neutral": {
      "50": "#fafafa",
      "100": "#f5f5f5",
      "200": "#eeeeee",
      "300": "#e0e0e0",
      "400": "#bdbdbd",
      "500": "#9e9e9e",
      "600": "#757575",
      "700": "#616161",
      "800": "#424242",
      "900": "#212121",
      "950": "#1b1b1b"
    },
    "semantic": {
      "success": "#4caf50",
      "error": "#f44336",
      "warning": "#ff9800",
      "info": "#2196f3"
    }
  },
  "typography": {
    "fontFamily": {
      "sans": [
        "Roboto",
        "Helvetica",
        "Arial",
        "sans-serif"
      ],
      "serif": [
        "Merriweather",
        "serif"
      ],
      "mono": [
        "Courier New",
        "Courier",
        "monospace"
      ]
    },
    "fontSize": {
      "xs": "0.75rem",
      "sm": "0.875rem",
      "base": "1rem",
      "lg": "1.125rem",
      "xl": "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "3.75rem"
    }
  },
  "spacing": {
    "0": "0px",
    "1": "0.25rem",
    "2": "0.5rem",
    "3": "0.75rem",
    "4": "1rem",
    "5": "1.25rem",
    "6": "1.5rem",
    "8": "2rem",
    "10": "2.5rem",
    "12": "3rem",
    "16": "4rem",
    "20": "5rem",
    "24": "6rem",
    "32": "8rem",
    "40": "10rem",
    "48": "12rem",
    "56": "14rem",
    "64": "16rem"
  }
};

export const colors = designTokens.colors || {};
export const typography = designTokens.typography || {};
export const spacing = designTokens.spacing || {};
export const borderRadius = designTokens.borderRadius || {};
export const shadows = designTokens.shadows || {};
